### ISSUE TITLE
Unknown Instruction

### ISSUE THREAD

**Issue by MarioLover63** [captainsouthbird/SMB3Utilties#4]
every single line of the game.xml fil is marked as an Unknown Instruction

**Comment by MarioLover63** [comment]
Also, NoDice wont start because ACCESS DENIED

**Comment by captainsouthbird** [comment]
Those sound like local permission problems. In any case, I've decided not to maintain these utilities any further simply because Mario 3 hacking is no longer on my radar, and these utilities by and large could use a rewrite.
